CREATE TABLE question_details (
  id INT NOT NULL AUTO_INCREMENT,
  question_id INT NOT NULL,
  question_text TEXT NOT NULL,
  correct_answer ENUM('a', 'b', 'c', 'd') NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE
) ENGINE = InnoDB;