CREATE TABLE answers (
  id INT NOT NULL AUTO_INCREMENT,
  question_detail_id INT NOT NULL,
  answer TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (question_detail_id) REFERENCES question_details(id) ON DELETE CASCADE
) ENGINE = InnoDB;