CREATE TABLE user_answers (
  id INT NOT NULL AUTO_INCREMENT,
  answer_id INT NOT NULL,
  question_id INT NOT NULL,
  user_id INT NOT NULL,
  quizz_id INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (answer_id) REFERENCES answers(id) ON DELETE CASCADE,
  FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (quizz_id) REFERENCES quizzes(id) ON DELETE CASCADE
) ENGINE = InnoDB;