CREATE TABLE courses (
  course_code VARCHAR(3) NOT NULL UNIQUE,
  name VARCHAR(180) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (course_code)
) ENGINE = InnoDB;