CREATE TABLE question_details (
  id INT NOT NULL AUTO_INCREMENT,
  question_id INT NOT NULL,
  question TEXT NOT NULL,
  answer_id INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE
) ENGINE = InnoDB;